In [62]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

Datasets downloaded from https://datasets.imdbws.com

In [14]:
title_df = pd.read_csv('/Users/parkerharalds/Downloads/title.basics.tsv', delimiter='\t')

/var/folders/0k/y2qbjrj17tx6k7cdjb67jg100000gn/T/ipykernel_46058/1126940356.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  title_df = pd.read_csv('/Users/parkerharalds/Downloads/title.basics.tsv', delimiter='\t')

In [15]:
#checking for top grossing movie
title_df[title_df['primaryTitle']=='Star Wars: Episode VII - The Force Awakens']

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
6117964,tt2488496,movie,Star Wars: Episode VII - The Force Awakens,Star Wars: Episode VII - The Force Awakens,0,2015,\N,138,"Action,Adventure,Sci-Fi"
9105905,tt5289954,tvEpisode,Star Wars: Episode VII - The Force Awakens,Star Wars: Episode VII - The Force Awakens,0,2015,\N,34,"Documentary,Short"

In [16]:
title_df['titleType'].unique()

array(['short', 'movie', 'tvShort', 'tvMovie', 'tvEpisode', 'tvSeries',
       'tvMiniSeries', 'tvSpecial', 'video', 'videoGame', 'tvPilot'],
      dtype=object)

In [17]:
movie_title = title_df[title_df['titleType']=='movie']

In [81]:
movie_title[movie_title['primaryTitle']=='Star Wars: Episode VII - The Force Awakens']

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
6117964,tt2488496,movie,Star Wars: Episode VII - The Force Awakens,Star Wars: Episode VII - The Force Awakens,0,2015,\N,138,"Action,Adventure,Sci-Fi"

In [82]:
ratings_df = pd.read_csv('/Users/parkerharalds/Downloads/title.ratings.tsv', delimiter='\t')
# ratings_df

In [83]:
cast_df = pd.read_csv('/Users/parkerharalds/Downloads/title.crew.tsv', delimiter='\t')
# cast_df

In [84]:
name_df = pd.read_csv('/Users/parkerharalds/Downloads/name.basics.tsv', delimiter='\t')
# name_df

Will now merge df together to get main_df

In [25]:
movies = pd.merge(movie_title,ratings_df,on='tconst')

In [27]:
movie_df = pd.merge(movies,cast_df,on='tconst')

In [29]:
#renaming directors column for merge
movie_df = movie_df.rename(columns={'directors':'nconst'})

In [89]:
main_df = pd.merge(movie_df,name_df,on='nconst')

In [91]:
main_df[main_df['primaryTitle']=='Star Wars: Episode VII - The Force Awakens']

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,nconst,writers,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
211865,tt2488496,movie,Star Wars: Episode VII - The Force Awakens,Star Wars: Episode VII - The Force Awakens,0,2015,\N,138,"Action,Adventure,Sci-Fi",7.8,986211,nm0009190,"nm0001410,nm0009190,nm1578335,nm0000184",J.J. Abrams,1966,\N,"producer,writer,music_department","tt0411008,tt0796366,tt2488496,tt2527338"

In [32]:
main_df.sort_values(by='numVotes',ascending=False).head(50)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,nconst,writers,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
57834,tt0111161,movie,The Shawshank Redemption,The Shawshank Redemption,0,1994,\N,142,Drama,9.3,2956432,nm0001104,"nm0000175,nm0001104",Frank Darabont,1959,\N,"writer,producer,director","tt0120689,tt0111161,tt0884328,tt1520211"
127879,tt0468569,movie,The Dark Knight,The Dark Knight,0,2008,\N,152,"Action,Crime,Drama",9.0,2938168,nm0634240,"nm0634300,nm0634240,nm0275286,nm0004170",Christopher Nolan,1970,\N,"writer,producer,director","tt6723592,tt0816692,tt1375666,tt0482571"
164712,tt1375666,movie,Inception,Inception,0,2010,\N,148,"Action,Adventure,Sci-Fi",8.8,2607377,nm0634240,nm0634240,Christopher Nolan,1970,\N,"writer,producer,director","tt6723592,tt0816692,tt1375666,tt0482571"
67080,tt0137523,movie,Fight Club,Fight Club,0,1999,\N,139,Drama,8.8,2388636,nm0000399,"nm0657333,nm0880243",David Fincher,1962,\N,"producer,director,writer","tt0114369,tt0443706,tt2267998,tt1285016"
57144,tt0109830,movie,Forrest Gump,Forrest Gump,0,1994,\N,142,"Drama,Romance",8.8,2313586,nm0000709,"nm0343165,nm0744839",Robert Zemeckis,1952,\N,"producer,writer,director","tt0088763,tt0109830,tt0118884,tt1907668"
57693,tt0110912,movie,Pulp Fiction,Pulp Fiction,0,1994,\N,154,"Crime,Drama",8.9,2270544,nm0000233,"nm0000233,nm0000812",Quentin Tarantino,1963,\N,"producer,writer,actor","tt0105236,tt0110912,tt0116367,tt7131622"
133180,tt0816692,movie,Interstellar,Interstellar,0,2014,\N,169,"Adventure,Drama,Sci-Fi",8.7,2183243,nm0634240,"nm0634300,nm0634240",Christopher Nolan,1970,\N,"writer,producer,director","tt6723592,tt0816692,tt1375666,tt0482571"
34529,tt0068646,movie,The Godfather,The Godfather,0,1972,\N,175,"Crime,Drama",9.2,2061054,nm0000338,"nm0701374,nm0000338",Francis Ford Coppola,1939,\N,"producer,director,writer","tt0078788,tt0071360,tt0071562,tt0068646"
62222,tt0120737,movie,The Lord of the Rings: The Fellowship of the Ring,The Lord of the Rings: The Fellowship of the Ring,0,2001,\N,178,"Action,Adventure,Drama",8.9,2053933,nm0001392,"nm0866058,nm0909638,nm0101991,nm0001392",Peter Jackson,1961,\N,"producer,director,writer","tt0120737,tt0092610,tt0167260,tt0167261"
73825,tt0167260,movie,The Lord of the Rings: The Return of the King,The Lord of the Rings: The Return of the King,0,2003,\N,201,"Action,Adventure,Drama",9.0,2024105,nm0001392,"nm0866058,nm0909638,nm0101991,nm0001392",Peter Jackson,1961,\N,"producer,director,writer","tt0120737,tt0092610,tt0167260,tt0167261"
162728,tt1345836,movie,The Dark Knight Rises,The Dark Knight Rises,0,2012,\N,164,"Action,Drama,Thriller",8.4,1867053,nm0634240,"nm0634300,nm0634240,nm0275286,nm0004170",Christopher Nolan,1970,\N,"writer,producer,director","tt6723592,tt0816692,tt1375666,tt0482571"
59227,tt0114369,movie,Se7en,Se7en,0,1995,\N,127,"Crime,Drama,Mystery",8.6,1846570,nm0000399,nm0001825,David Fincher,1962,\N,"producer,director,writer","tt0114369,tt0443706,tt2267998,tt1285016"
73826,tt0167261,movie,The Lord of the Rings: The Two Towers,The Lord of the Rings: The Two Towers,0,2002,\N,179,"Action,Adventure,Drama",8.8,1824878,nm0001392,"nm0866058,nm0909638,nm0101991,nm0801728,nm0001392",Peter Jackson,1961,\N,"producer,director,writer","tt0120737,tt0092610,tt0167260,tt0167261"
190435,tt1853728,movie,Django Unchained,Django Unchained,0,2012,\N,165,"Comedy,Drama,Western",8.5,1736754,nm0000233,nm0000233,Quentin Tarantino,1963,\N,"producer,writer,actor","tt0105236,tt0110912,tt0116367,tt7131622"
75017,tt0172495,movie,Gladiator,Gladiator,0,2000,\N,155,"Action,Adventure,Drama",8.5,1667675,nm0000631,"nm0291905,nm0517589,nm0629933",Ridley Scott,1937,\N,"producer,director,production_designer","tt3659388,tt0083658,tt0103074,tt2193215"
137593,tt0993846,movie,The Wolf of Wall Street,The Wolf of Wall Street,0,2013,\N,180,"Biography,Comedy,Crime",8.2,1629416,nm0000217,"nm1010540,nm0067789",Martin Scorsese,1942,\N,"producer,director,actor","tt5537002,tt0075314,tt0070379,tt0099685"
114587,tt0361748,movie,Inglourious Basterds,Inglourious Basterds,0,2009,\N,153,"Adventure,Drama,War",8.4,1625375,nm0000233,nm0000233,Quentin Tarantino,1963,\N,"producer,writer,actor","tt0105236,tt0110912,tt0116367,tt7131622"
116351,tt0372784,movie,Batman Begins,Batman Begins,0,2005,\N,140,"Action,Crime,Drama",8.2,1609815,nm0634240,"nm0004170,nm0275286,nm0634240",Christopher Nolan,1970,\N,"writer,producer,director","tt6723592,tt0816692,tt1375666,tt0482571"
53810,tt0102926,movie,The Silence of the Lambs,The Silence of the Lambs,0,1991,\N,118,"Crime,Drama,Thriller",8.6,1586744,nm0001129,"nm0365383,nm0848217",Jonathan Demme,1944,2017,"director,producer,writer","tt0102926,tt1084950,tt0107818,tt0368008"
269310,tt7286456,movie,Joker,Joker,0,2019,\N,122,"Crime,Drama,Thriller",8.4,1553819,nm0680846,"nm0680846,nm0798788,nm0004170,nm0277730,nm1047603",Todd Phillips,1970,\N,"producer,director,writer","tt7286456,tt1231583,tt0302886,tt0215129"
62276,tt0120815,movie,Saving Private Ryan,Saving Private Ryan,0,1998,\N,169,"Drama,War",8.6,1528623,nm0000229,nm0734441,Steven Spielberg,1946,\N,"producer,writer,director","tt0108052,tt0083866,tt0120815,tt0082971"
147568,tt1130884,movie,Shutter Island,Shutter Island,0,2010,\N,138,"Drama,Mystery,Thriller",8.2,1499599,nm0000217,"nm0436164,nm1212331",Martin Scorsese,1942,\N,"producer,director,actor","tt5537002,tt0075314,tt0070379,tt0099685"
56357,tt0108052,movie,Schindler's List,Schindler's List,0,1993,\N,195,"Biography,Drama,History",9.0,1482912,nm0000229,"nm0447745,nm0001873",Steven Spielberg,1946,\N,"producer,writer,director","tt0108052,tt0083866,tt0120815,tt0082971"
134346,tt0848228,movie,The Avengers,The Avengers,0,2012,\N,143,"Action,Sci-Fi",8.0,1481571,nm0923736,"nm0923736,nm0672015",Joss Whedon,1964,\N,"producer,writer,director","tt0118276,tt0848228,tt1259521,tt0162065"
39408,tt0076759,movie,Star Wars: Episode IV - A New Hope,Star Wars,0,1977,\N,121,"Action,Adventure,Fantasy",8.6,1476113,nm0000184,nm0000184,George Lucas,1944,\N,"writer,producer,director","tt0076759,tt0066434,tt0069704,tt0082971"
129459,tt0482571,movie,The Prestige,The Prestige,0,2006,\N,130,"Drama,Mystery,Sci-Fi",8.5,1473273,nm0634240,"nm0634300,nm0634240,nm1793993",Christopher Nolan,1970,\N,"writer,producer,director","tt6723592,tt0816692,tt1375666,tt0482571"
120954,tt0407887,movie,The Departed,The Departed,0,2006,\N,151,"Crime,Drama,Thriller",8.5,1450255,nm0000217,"nm1184258,nm0538320,nm0159039",Martin Scorsese,1942,\N,"producer,director,actor","tt5537002,tt0075314,tt0070379,tt0099685"
62190,tt0120689,movie,The Green Mile,The Green Mile,0,1999,\N,189,"Crime,Drama,Fantasy",8.6,1441581,nm0001104,"nm0000175,nm0001104",Frank Darabont,1959,\N,"writer,producer,director","tt0120689,tt0111161,tt0884328,tt1520211"
41618,tt0080684,movie,Star Wars: Episode V - The Empire Strikes Back,Star Wars: Episode V - The Empire Strikes Back,0,1980,\N,124,"Action,Adventure,Fantasy",8.7,1407238,nm0449984,"nm0102824,nm0001410,nm0000184",Irvin Kershner,1923,2010,"director,cinematographer,actor","tt0080684,tt0110725,tt0086006,tt0100502"
131178,tt0499549,movie,Avatar,Avatar,0,2009,\N,162,"Action,Adventure,Fantasy",7.9,1406740,nm0000116,nm0000116,James Cameron,1954,\N,"writer,producer,director","tt0499549,tt1630029,tt0090605,tt0103064"
36348,tt0071562,movie,The Godfather Part II,The Godfather Part II,0,1974,\N,202,"Crime,Drama",9.0,1392494,nm0000338,"nm0000338,nm0701374",Francis Ford Coppola,1939,\N,"producer,director,writer","tt0078788,tt0071360,tt0071562,tt0068646"
85194,tt0209144,movie,Memento,Memento,0,2000,\N,113,"Mystery,Thriller",8.4,1347041,nm0634240,"nm0634240,nm0634300",Christopher Nolan,1970,\N,"writer,producer,director","tt6723592,tt0816692,tt1375666,tt0482571"
46114,tt0088763,movie,Back to the Future,Back to the Future,0,1985,\N,116,"Adventure,Comedy,Sci-Fi",8.5,1339441,nm0000709,"nm0000709,nm0301826",Robert Zemeckis,1952,\N,"producer,writer,director","tt0088763,tt0109830,tt0118884,tt1907668"
61986,tt0120338,movie,Titanic,Titanic,0,1997,\N,194,"Drama,Romance",7.9,1310362,nm0000116,nm0000116,James Cameron,1954,\N,"writer,producer,director","tt0499549,tt1630029,tt0090605,tt0103064"
195511,tt2015381,movie,Guardians of the Galaxy,Guardians of the Galaxy,0,2014,\N,121,"Action,Adventure,Comedy",8.0,1293777,nm0348181,"nm0348181,nm2270979,nm3966115,nm5037683,nm2757...",James Gunn,1966,\N,"writer,producer,director","tt2015381,tt3896198,tt1333125,tt0439815"
52124,tt0099685,movie,Goodfellas,Goodfellas,0,1990,\N,145,"Biography,Crime,Drama",8.7,1286836,nm0000217,"nm0683380,nm0000217",Martin Scorsese,1942,\N,"producer,director,actor","tt5537002,tt0075314,tt0070379,tt0099685"
57436,tt0110413,movie,Léon: The Professional,Léon,0,1994,\N,110,"Action,Crime,Drama",8.5,1271487,nm0000108,nm0000108,Luc Besson,1959,\N,"writer,producer,director","tt0119116,tt0110413,tt2872732,tt0100263"
109132,tt0325980,movie,Pirates of the Caribbean: The Curse of the Bla...,Pirates of the Caribbean: The Curse of the Bla...,0,2003,\N,143,"Action,Adventure,Fantasy",8.1,1235838,nm0893659,"nm0254645,nm0744429,nm0064181,nm0938684",Gore Verbinski,1964,\N,"director,producer,writer","tt1192628,tt0325980,tt4731136,tt1210819"
62014,tt0120382,movie,The Truman Show,The Truman Show,0,1998,\N,103,"Comedy,Drama",8.2,1233697,nm0001837,nm0629272,Peter Weir,1944,\N,"director,writer,producer","tt0311113,tt1023114,tt0090329,tt0097165"
74309,tt0169547,movie,American Beauty,American Beauty,0,1999,\N,122,Drama,8.3,1228084,nm0005222,nm0050332,Sam Mendes,1965,\N,"producer,director,miscellaneous","tt8579674,tt0257044,tt1074638,tt0959337"
135842,tt0910970,movie,WALL·E,WALL·E,0,2008,\N,98,"Adventure,Animation,Family",8.4,1227575,nm0004056,"nm0004056,nm0230032,nm0714114",Andrew Stanton,1965,\N,"writer,producer,actor","tt0910970,tt0266543,tt2277860,tt0120623"
97374,tt0266697,movie,Kill Bill: Vol. 1,Kill Bill: Vol. 1,0,2003,\N,111,"Action,Crime,Thriller",8.2,1220616,nm0000233,"nm0000233,nm0000235",Quentin Tarantino,1963,\N,"producer,writer,actor","tt0105236,tt0110912,tt0116367,tt7131622"
62126,tt0120586,movie,American History X,American History X,0,1998,\N,119,"Crime,Drama",8.5,1206566,nm0443411,nm0571346,Tony Kaye,1952,\N,"director,cinematographer,producer","tt1683526,tt0841119,tt0120586,tt28246392"
53880,tt0103064,movie,Terminator 2: Judgment Day,Terminator 2: Judgment Day,0,1991,\N,137,"Action,Adventure,Sci-Fi",8.6,1200014,nm0000116,"nm0000116,nm0936537",James Cameron,1954,\N,"writer,producer,director","tt0499549,tt1630029,tt0090605,tt0103064"
124169,tt0434409,movie,V for Vendetta,V for Vendetta,0,2005,\N,132,"Action,Drama,Sci-Fi",8.1,1195235,nm0574625,"nm0905152,nm0905154,nm2331222",James McTeigue,\N,\N,"director,producer,assistant_director","tt0434409,tt1486192,tt1186367,tt0133093"
168640,tt1431045,movie,Deadpool,Deadpool,0,2016,\N,108,"Action,Comedy",8.0,1174554,nm1783265,"nm1014201,nm1116660",Tim Miller,1964,\N,"producer,writer,director","tt9561862,tt6450804,tt1431045,tt4978420"
59412,tt0114814,movie,The Usual Suspects,The Usual Suspects,0,1995,\N,106,"Crime,Drama,Mystery",8.5,1164275,nm0001741,nm0003160,Bryan Singer,1965,\N,"producer,director,actor","tt0120903,tt0114814,tt0348150,tt1877832"
116189,tt0371746,movie,Iron Man,Iron Man,0,2008,\N,126,"Action,Adventure,Sci-Fi",7.9,1147456,nm0269463,"nm1318843,nm1319757,nm1436466,nm0391344,nm0498...",Jon Favreau,1966,\N,"producer,actor,writer","tt2883512,tt0371746,tt0117802,tt8111088"
44778,tt0086190,movie,Star Wars: Episode VI - Return of the Jedi,Star Wars: Episode VI - Return of the Jedi,0,1983,\N,131,"Action,Adventure,Fantasy",8.3,1141372,nm0549658,"nm0001410,nm0000184",Richard Marquand,1937,1987,"director,producer,writer","tt0086190,tt0107711,tt0089360,tt1043199"
165865,tt1392190,movie,Mad Max: Fury Road,Mad Max: Fury Road,0,2015,\N,120,"Action,Adventure,Sci-Fi",8.1,1135998,nm0004306,"nm0004306,nm0565068,nm0490147",George Miller,1945,\N,"producer,writer,director","tt1392190,tt0082694,tt0079501,tt0366548"

reading in revenue data from The-Numbers (hand copied to avoid violating their policy)

In [231]:
num_df = pd.read_csv('Data/revenue.csv')

In [232]:
num_df = num_df.rename(columns={'Movie':'primaryTitle'})

In [233]:
num_df['title'] = num_df['primaryTitle'].str.replace(r'[:/.-]', '', regex=True)

Star wars movies are very prevelant in the top budget/revenue dataset. There is a slight naming descrepency between IMDB and the-numbers for these movies. Fixing that:

In [234]:
num_df['title'] = num_df['title'].str.replace('Ep', 'Episode', regex=True).str.lower()

In [215]:
main_df1 = main_df

In [216]:
main_df1['title'] = main_df1['primaryTitle'].str.replace(r'[:/.-]', '', regex=True).str.lower()

PROBLEM 1:

Need to make new nameid column with title and year? Some movies were remakes or have duplicate names. This means I can't merge revenue data

In [235]:
num_df1 = num_df.rename(columns={'Release\nDate':'date','Production\nBudget':'budget',
                                'Domestic\nGross':'domestic_gross','Worldwide\nGross':'world_gross'})

num_df = num_df1

In [236]:
num_df['date'] = pd.to_datetime(num_df['date'])

In [237]:
num_df['year'] = num_df['date'].dt.year

In [238]:
num_df['name_id'] = num_df['title'] + num_df['year'].astype(str)

In [188]:
main_df['name_id'] = main_df['primaryTitle'] + main_df['startYear']

In [239]:
df = pd.merge(num_df,main_df, on='name_id')

In [241]:
df[df['primaryTitle_x']=='Mad Max']

,Rank,date,primaryTitle_x,budget,domestic_gross,world_gross,title_x,year,name_id,tconst,...,averageRating,numVotes,nconst,writers,primaryName,birthYear,deathYear,primaryProfession,knownForTitles,title_y
59,"6,353",1979-04-12,Mad Max,"$200,000","$8,750,000","$99,750,000",mad max,1979,mad max1979,tt0079501,...,6.8,234333,nm0004306,"nm0565537,nm0004306,nm0447945",George Miller,1945,\N,"producer,writer,director","tt1392190,tt0082694,tt0079501,tt0366548",mad max

FuzzyWuzzy

In [192]:
df.columns

Index(['Rank', 'date', 'primaryTitle_x', 'budget', 'domestic_gross',
       'world_gross', 'title_x', 'year', 'name_id', 'tconst', 'titleType',
       'primaryTitle_y', 'originalTitle', 'isAdult', 'startYear', 'endYear',
       'runtimeMinutes', 'genres', 'averageRating', 'numVotes', 'nconst',
       'writers', 'primaryName', 'birthYear', 'deathYear', 'primaryProfession',
       'knownForTitles', 'title_y'],
      dtype='object')